on:
  push:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello GitHub Actions"
      - name: Show Info
        run: |
          echo "Branch : ${{ github.ref_name }}"
          echo "Commit : ${{ github.sha }}"

